export const ENlabels = {
    themeDark: 'Dark',
    themeLight: 'Light',
    languaje: 'Languaje',
    userTitle: 'Alexis Eduardo Matamoros',
    userJob: 'Web Developer',
    options: 'Options',
    mainTitle: 'About Me',
    mainMsg: `My name is Alexis Matamoros, Systems Engineer with an enthusiastic soul
  skills are focused on the development of web applications, I invite you to get to know me a little.`,
    mainHero: `Hi! welcome to mi world.`,
    cvButton: 'Download CV',
    frase: `"No matter how high is a mountain, there is always a way to the top."`,
    homeTitle: 'Home',
    blogTitle: 'Blog',
    tecnologiesTitle: 'Tecs',
    contactTitle: 'Contact',
    proyectsTitle: 'Proyects',
    techsTitle: 'Techs',
    experience: 'Experience',
    footerText: 'Generated with REACT, TailwindCSS, VSCode and a lot of love.',
    contactFullName: 'Full Name',
    contactEmail: 'Your email',
    contactSubject: 'Tell me, how can i help you?',
};
