export const ESlabels = {
    themeDark: 'Oscuro',
    themeLight: 'Original',
    languaje: 'Idioma',
    userTitle: 'Alexis Eduardo Matamoros',
    userJob: 'Desarrollador Web',
    options: 'Opciones',
    mainTitle: 'Sobre Mi',
    mainMsg: `Mi nombre es Alexis Matamoros, soy Ingeniero en Sistemas con un alma entusiasta mis
  habilidades están enfocadas en el desarrollo de aplicaciones web, te invito a conocerme un poco.`,
    mainHero: `¡Hola!, bienvenido a mi mundo`,
    cvButton: 'Descargar CV',
    frase: `"No importa que tan alta es la montaña, siempre hay un camino a la cima."`,
    homeTitle: 'Inicio',
    blogTitle: 'Blog',
    tecnologiesTitle: 'Tecnologias',
    contactTitle: 'Contacto',
    proyectsTitle: 'Proyectos',
    techsTitle: 'Tecnologias',
    experience: 'Experiencia',
    footerText: 'Generado con REACT, TailwindCSS, VSCode y mucho amor.',
    contactFullName: 'Nombre',
    contactEmail: 'Correo',
    contactSubject: 'Dime, ¿Cómo puedo ayudarte?',
};
