name: Deploy to vercel on push

on:
    push:
        branches:
            - main

jobs:
    ejecutar-script:
        runs-on: ubuntu-latest

        steps:
            - name: Instalar dependencias
              run: npm install

            - name: Ejecutar script desde package.json
              run: npm run deploy
